name: CI

on:
  push:
    branches: [ "**" ]
    tags-ignore: [ "**" ]
    paths-ignore:
      - "**/*.md"
      - "**/*.png"
      - "**/*.jpg"
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ "**" ]

permissions:
  contents: read

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: step-security/harden-runner@v2
        with: { egress-policy: audit }
      - uses: gradle/wrapper-validation-action@v2
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle
      - uses: gradle/actions/setup-gradle@v4

      - name: Build
        run: ./gradlew --no-daemon clean build

      - name: Testes
        run: ./gradlew --no-daemon test